#
# Deploys all-in-one controller + core pomerium
#
resources:
- namespace.yaml
- ./ingressclass.yaml
- ./deployment
- ./service
- ./rbac
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
